---
title: "Formosan languages: R and corpus-based studies"
author: "Aymeric Collart"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is the website of the tutorial on Formosan languages, corpus-based studies and R/RStudio."
---

# Welcome to the tutorial on "Formosan languages, corpus and R/RStudio"

## Objectives of the tutorial

In this tutorial, you will learn:

-   how to download data from the Internet automatically and quickly,

-   how to process the downloaded data without spending a lot of time with manual tasks,

-   how to create summary tables and images to analyze your data.

## Who is this tutorial for?

### **1- Do I need any background?**

You do not need any particular background.

This tutorial will start with the very basics. If you are already familiar with coding and/or the RStudio interface, it will of course be easier for you.

### **2- Which public?**

Anyone interested in Formosan languages^[[1]](https://aymeric-courses.github.io/formosan-corpus-r/#footnote1)^ is welcome to take this tutorial, regardless if you are an undergraduate or graduate student, research assistant or just curious about quantitative methods and Formosan languages.

## News

**Note:** The webpage of this tutorial has just been created. That's why it looks quite empty and some pages not at their right place. Stay tuned for further developments!

------------------------------------------------------------------------

[1] I use the term 'Formosan languages' as the Austronesian languages from Taiwan, including Yami (even though from a typological perspective, Yami is not a Formosan language).
